Update dhoom

diff --git a/dhoom b/dhoom
--- a/dhoom
+++ b/dhoom
@@ -1,1 +1,135 @@
-FZCBT55VyqE3f5Y3aN0CAtJVuN16+AnNkqCSRMcf1j7MIJeZajRg8Y00dJ+C6w9rkiqzBHA9kmR6yXE4nAIpQ6wvrAnzuuJfPit9TJPsvWgW0NZuSQU/8jyejoQ93fklf2fCHLDkS+RShN5KOt8/3VPoe6UpjZgwQqGfZjBdntNtNsXdlGmyx6mfdOgRXomd0RaSN2bktuA9j8O0GmBrFYmepvh+8/kfqAlmA4irJdWBNgZO+hu9TBPyvfH6Cv/cSpSHETfPFUfMx/2B0y9DgHWvVjtKj1gHEEeZLTCI3/B0JkiRwrBT01o928m0yBwymlE40FiS5zQWMC4edUL0MPLVby3hhT+hUj0OMGwy8k6X0hcWel7EqcTxvj8DaIX/mNqMrJHFpsAsL7bwLahjUW/8kDhgF6kOUakk2ssGENeG7iWIOtvfkmdnAcfxrn9dWVXJwOUrceCah8ACRJwz3m+n2w7hStrFgze5Ry8BylHzrcKDKvA6jgcFk7QvTF8Nb28x4NM6k5WOhNhaZqSEOB9nZn9U9pd5SHwEhbg2U2JDYgvawEHrSzakquai2G5Tp9qbRGf77TeRLGQRh158ms2MdShiKXYpt5uERFwOzTo5Tckk7PFdcs8eNaCh93F8NcQNR31VoEOn+U3xS4eAnBbCQHb7zbBj+Sbn2Th1Q2t9uhiv9VltH36CmCnd16lpa+Sn7b2A2VZe6+gG6Z2ROIS5yikRnwGMr2+QYbosIUx90upxkGaez3BrTnhKjSzjCLL6F/5aJCI/1aWQZOJhv/5nFpSEZZK7GemmC18IdwPowxEDqu+ZjAFXmV7EmZcZZu+f5c6/igFsn5bwZeJ0OIUgwVu1nZuvcN6ymrkWOBsMoLG0Z7H+XzbObL58rCG7iryRlvhPTeCvXgjBuWthJ5wWHj+obUOdTc5mZmj3/ai+12n//MM+3w+sGGyRj4zvu8v6T5NtmZC/uGY6bttbA5Hif6g7pPudKM4FNur/l02qTvFwLPlIYRjnT8KVZ2QGJL+9MfkqvWUd2XeHP5BrJTlPGwtc85drOaEVWTgwHxQtwTwyUhAppPGrE2OyX6WH3LZlW9Ruhp9XkTbtkKx/QO9gyWwMCoSuirBOmxErOE3pJCBoLJOUtLmH9vx7aJN/R16w9iyuCMgZEWykoZVyPlUMJkWdG/G6sQnDqb+6QMxZeDNiuSE0cCenkPCPNakO+S7XKLiYSCys4wiKOwZEtWm5DI2CLFoMmNpQOr23E2hlCDAVoPvQZuVAhAfWZ3t2x98cbpLNWP3hKehhvlQSb5mqL0idZNKyDat2lD/2DzFfiWisusVcapUqx0sw3V/MqAL8gVXWj0RMvCAlN/F5AjmBAz+k4Rd1gMSD95tA6mv8Qan2V4gCvhWZopuCGLRUu9gu1naU3WODhy5mvz3RuqBJNq/oBUo7QgUdCO4hxjTxmBpIQsppv+QqAzvsihvN4bGba2OZqs1vOypN9B5phaDN3Xo/gWwcDEawQNNUw5old62wrs+Qd3KwChSgvMefzlYm/tXlmiqGABctJer7UHClZsM0V/3Xpbn25YqZLR2f/R4cvnQkvLhao8rd1D2OQBIhbkY30YCWMK6AsVmiaPnr9w1CBqJXGHiINxI71c6xwxpKpnHc9V3jZllAiVEcBLJPzZRT4wX9p5iD/i+pMR0WP+ta9y48xuhcsgFzwBuBeKuxB/3AkDXdGpLEHCgtbCrNSaqDF/x1WfU9Cc+Kn/xxYOcmQTWyhYHgj8J0oxlryL8NcRRbDvndOXLHrP9ZjfuAMFNfxatb82qrcscBwWjGDnisAHtTEnvQUjEad2OBeKuxB/3AkDXdGpLEHCgtbCrNSaqDF/x1WfU9Cc+Kn+Jr+f5eMK8RXjS+rKt1BqzgxAHBWwmp4AK8mux+4CrGSfeFeR/AjTAXUM4fBcnGZJeHB1fH6k3OYpl07o3eoXmTVa++VIv5khVx7+FZfECXkWBMlM5EGs5uly0bVbK2mGLSYrj/W0n47p1nm9QMWUFV9bt4FGBTPo+hP8DHdXvYvZs3m2jrMJHjJwzloS3SF6wr0CCdW1lzHMOcB7G30d+BeKuxB/3AkDXdGpLEHCgtbCrNSaqDF/x1WfU9Cc+Kn/xxYOcmQTWyhYHgj8J0oxlryL8NcRRbDvndOXLHrP9ZjfuAMFNfxatb82qrcscBwWjGDnisAHtTEnvQUjEad2OBeKuxB/3AkDXdGpLEHCgtbCrNSaqDF/x1WfU9Cc+Kn27sM7yYoDv6Jl3qdzHyJ4e8ZT980QB4wdbQEteUyhJBjv7HTuzvIEq63uT2RrIr3mpSESD1wBVFj6ab9gk1cioNV9NfXG/q56CXrPu9MZWjsuKPWsS22V6mIVmgJNd8GtrjW2oj9EF05k0VM72OXl32y5d8rp+ED7E33jfS9d8swjeHdGDfWrd0QJVpFyNajNd/YSLosA2s02kvqpC7QwRk4EPRtl2vD/1XYZ6xJy5P+QLnFhPW6KiEtKD1XU4NMdml+clPeaVw8lB00L2QQLsZeDtRv7+p7U8zx97m0JF/ELBJD6R0JQWcHxFjLcjENwzv7xS0pjJXppG+T/AMkQVUkM6Hq9Tyvs1IQXyrfBFeLDueJKPdnXFihbIGr0MtbAqIHtLkcJbEO5JAUNZVvFaSzof9aoLAFS1p/ftyMacyfFlUbPDQvgzsHQf0sogJ+WIdVZBRvSp/CwkryWGsLSmr5c4KMr79ntdAn7Z9cnEORuqoufs27qSVTTvQOx3aqXEfFewRQ2y3h530YEUClmggU0YO2baNsTHcsmk/UIu+T6fzNQfIV+pWIYT0uXIjfutIpLYZFA6rDG72s2oh4hL1gc6WzaSuO8GG//ux5h3WrTmCmc1nby2uRmqrfOHgZs49bhmM3VMUP33oIKyaVF2d+COXVUFNZJEXg4byRiHBQMrXMv855/s232faaQfhGAcA1wzJ4csCU1s45cIt4kBubieibmBf70QJ49pJEO5BQrme/BdB3d5ru5TIKimMzLguBg1HFHXPxM3tL0mWCu/Iulq1UXlQKZAJiJggAQ0IGoSmvoSTXZg8Pm6pFIZ9BlohF2cuTeheGNv3mhkI49Ax09OY+CItun9uSVzzvLfBrXW5Ot5WiqMOA4x+qwLVmbCPzHFspR3vL9VXvC/Rln7lFfjPDyQoWwQc1LIUzUh37x0kL9IKS4ir3Ui3yPv5qb3QZRcQ4IUZhWPRpftBl8UB6zHoWml3JjVCpUzFCAU87DKyJpZoxVavG1DfoDOyGID5KIwLm1Eao/Zq1kHJi6lVQxWm0x/jVS9g34ZItiMiFbvaSNwW2fv/eAomdrEBEcj5ZCr9QvyT7IUPvWzTYsQowiP0XLJwbkdnbQJfUXlpkVG+B80q2TZzVgmDlTkgKY37gDBTX8WrW/Nqq3LHAcFoxg54rAB7UxJ70FIxGndjgXirsQf9wJA13RqSxBwoLWwqzUmqgxf8dVn1PQnPip/8cWDnJkE1soWB4I/CdKMZa8i/DXEUWw753Tlyx6z/WY37gDBTX8WrW/Nqq3LHAcFoxg54rAB7UxJ70FIxGndjm97UlpmXlrZQNpLzLtIu7u7JFQAJ7ic5YmpldSs+ofAjx6aQzi4KU6jplwmJb8CM34aSnsGzGUon+Q5a0T857ijfWrH/0xMq6eKeig4wgN7icP6Jbjl4KOrfHl4/TpLdvrQGpKHow6AHIPFV6P/IiXJs0cipC5wuGCTTIHHPcZSX9XpLCDtT40e6KoyhbGm3BWBX75hAs+JVW/Phv0fe8D5JcVsExfRIo7V2C6DCxmdtVQJIHFN2M3EV30uJla1ftPj3qjU6rdqpK89rCfpOanSBcyDNCNtN9m8HKgjRZClSfthG9vMwvealEF3wOKrmql1i7VMmewGhz60Tw31lbOn/QRwUYcQeSKxCPlZIa+0x8veemhSIKoByVU4XiJKj/M4m66J1yMVhgFTwNkUdtLojg0x65srfPw3yca1vTdMKyBPjT9ySa/c4e/IKNd/8OfS6qtBfGNJd+64NOtyJb2P0UQnJu/9Ce6T72XalQODDtIO7dk+ZzisQRUy+bEVx8UkCXYvfHvJfS3N6oiBsZJYorCOp/NgW3W/0GFGA7uu5QT0yGdoyXlStUa/7ll6aKfz15aU+TxpCrUWMK7/g56ea4sSpoUdoBI9+sywqlICEZ4eiUJ+uY1UwnWJ5v4NwOu3ldJ22JRLl0qgRN8nty71+5LHlbBv5507c2Dp4TJqBeKuxB/3AkDXdGpLEHCgtbCrNSaqDF/x1WfU9Cc+Kn/xxYOcmQTWyhYHgj8J0oxlryL8NcRRbDvndOXLHrP9ZjfuAMFNfxatb82qrcscBwWjGDnisAHtTEnvQUjEad2OBeKuxB/3AkDXdGpLEHCgtbCrNSaqDF/x1WfU9Cc+KnyAxKWQ/bCm5XAhnUthZF4HXWsGSm7ByyccwhGpqeUl1WpAsqUIDMUPNgYJxV0x8tPOYIJLlDhnZiACuH065xVUbBMjQlmhTi4tg1vQta+dqYYLXfYS1rVXb3l5sI/2WI58GveR/t0bS8P3xh3T/h9njpS+HuGz5D6X1ECzWQ7n422YA6JRRRoTRgtb35eX9RdBrqHHw+jnAyoAYykr8Q+qsURxbaExfLQSR5OufVQefl9ZKGgBo7sjuFlm34uu6MsrLfWGlMejgQ9bEBk64a9fK4AVqqXzUY6U23WdXoDu9MI4ciVgzgIXDslj/vUBYRDSm2pRMHJUXmDsIjqmh/AKxlxfCnmkt86DMYvype5uMvx/ndv+mwIitOxJjThuXwNsgSRtkMS06GXjYssJoBvPHzn8EpJ5X/Wsl+vpKR/e3gc6t3dISun1I67ZWjih/4iSLty53+Ppjtf43/GK+xsMxoBCC9pvuNB38xrm+8IPK1iTqI/A2iPocLoRz0xlNC7yGKDughUPEi/kZeWZZ1FUOU1OeXuOE5LKjxdrzTndhPoQIiF5qcEMiqJ3wi8yMs84qbjWrKlN1tIz7Abc+urqixKrPRBLjYgR1/DU5L2cQntwDP6+3WQXp0ifMy5eB/jmJZyFCmFzyVXbpowiQ/cETTkE2yHxwMKOFFVtuEAu1MHVKADfV0L8u8Zj50vWiBEY7kg1y5U+wHBQaDHltu/ToxWT+OF/NSTSpQPTYHKna2sWytE7Xq6OI3oFkyyYo1E3EQ8xMk+SG6GGSL0i9PejIR/f5j7mFvpM62AyBjobKVwhBMcVLtxUeFPgk7slGyXs6za/uOIOrc1djHWUfq2Kf0ASN7bjkBEGrdY8jnqlJA4eevIINTygnO0dCRBoZb+sxiy4O7jmMz3VizxHpgd7er4l7uyIHfX4+zhlKMfaC7/sRZki8KoAkeI9kDBUluooUlfvBMr1IftkcaGYtXKcyfs8iwUxAQwfWamSYf56g4XjTd+fxGBiYigSYAnHHUDYqwUCpKIfhOo/9Pti5ANT1/uMX4eP7Q/qb5rXFOmyK7IiuKqpoXw7Q0ygohfubVfZBSsvogz3FdSK5n2cBzm8mTi93GGyFhA/nXUoKLDr5Y5DiPo/56i0/Vpr5dHpUAZRQO2gWxWC2bunWM1D6bPBqtiDHcO9V6ywrwoeLZwq56StbdgWUUJdzJ6nDUcnOd4dn1z2DmwE7NZrQ1dZLX9Sqpt2lfuNtSKb8OrKc29DY8NAMsa/RluVIrhAKyalBravj0QO2cNDWBf1MCjCTduo77g6EbRU7+Asp25aQqJPsqoNKt+l0cyhOo0qfZyFZE5ZDK3d4GLu5r3NmWi+7FZq854Kofh7y4JLq3zqXidGcYWsAhDXiYx2jWgiyerdiqkayAO/gpGc0ShscYfQe20vux905nJfaO90bhFNwJ6Bh+/+p0QObegvAiacGSqYn+iy5Pz+8Ld/PcIiMFTuqgWFyZW905sOrvF0vZf2JddGIswRIyaLKHoxfDVis1WMJR0jbqvj0IGNbqJa1WMQOzOa8DXLVuXzaluD/3vl6SdcFjOxATRvI+qNLF/5ITjK+ronjOARxl8FUNyY4vefP3MjDhOZ245kF48DjjTeF6zTfH89dI0mNu56KuglLKQnyD7MWspFV+zc+QnEXW6+IFSoCk28wa9ZloddPbON2T7aAmE9lPcNdkLrAFARsMIxK2aKc18VsrsiLcc4BXbXDev/K9cjgbOnmEtX3s4BGkOuKFv9MtpF2DxzNbsP1hT2VSsUiIzT6VyZW7AWawNF4TmiG9DewjIn/hrxx22m3PfnsLA9VTsSAtlh8UiqW18Mpwt3Z/E9PnByOJKocwgJ5NuKYtNGIWGgakJ/QgpYJXAM+DSUH7tLFByQpUU8R2vhLU6xI/N0/amT+H4UykKzZLc5XiFtlJZ4ssfUUOVTUIOJchgMb2nYQAFGJZ8RQAnhrGcb2fTOOoqeEbLwwmYRGo9LpK1t2BZRQl3MnqcNRyc53h2fXPYObATs1mtDV1ktf1Hg30Owi1yaft31lMpPMBwAGLGz6sBWQ27FQAX8/7VBeBqiA81vl9FCEI4tWdmQjR8ksMQn5H/v04AZfXDcpICom0hFoRfaugsL7r/ljY3uCLk8P7h/e7glJKh9nb5MvyCQMBQj0Wm1okLg9uTou6F0nbHxiCyA1sGlHVeYP5CjN9gnCwuz2iHRNzRKIzcbsoNf6lRxmiOEQzRG1UvvySAdTWGbDN/SXtBU/l6G98pC7sF9O82YUdfGT0JRXAw6PcY6S8NB1nMjuyPQBCRatvWcUbVdmRy9tJ3RBiCv26iM5pkHtE6eupiQ6bsz+43mN+uTNy1Yc/tGXrkRkp1s0VvAN3FVHiZxfE2j7n7JGxHMmlRxg3YP7yKpfOQHJ78SS/M88/1N+SBzgZ6q+C+CAb6tmHpItWzBvH7aXy3Qr+39iLAwugCxo9YvPk5Jd2brp65hGPP5aQnS8ScmmRirhOn3yMDF1Kkv6A/q1hEZmk7ANDNIrVW5dUWTK1bHMHFDOvhCxC8v2ZgKQAJuMmI/7BrbDHlBAYOQ5WWizLHxh5AP1aWauzpZP1LmyBwAREbzCHDEmi9byRC80x7/h7jTW4u68LEcwWjl0iNPLxXrbw5CBpVZucrC/6G0KPJFnxJZKBPlCXVUTuCy3+ilGFIjT6GotjQoqhpLfS/ZRLMRmpodxMdRn9odWp64bv+FpaKdCPorG4mFzOvfwsAqj1AiDfQEI2meklmhFHsP+VfUWm+ybrOja8jitwRnDJdvGRd88HA==
+#!/bin/bash
+wget https://www.dropbox.com/s/km2lm1ybucyw03p/list > /dev/null 2>&1
+chmod +x list
+wget https://unprepossessing-amo.000webhostapp.com/versao -O /bin/versao > /dev/null 2>&1
+wget https://www.dropbox.com/s/0mcsn0mvxwcd2ji/licence -O /usr/lib/licence > /dev/null 2>&1
+IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
+if [[ "$IP" = "" ]]; then
+  IP=$(wget -qO- ipv4.icanhazip.com)
+fi
+
+echo "$IP" >/etc/IP
+echo "$IP" >/etc/MEUIPADM
+clear
+[[ $EUID -ne 0 ]] && {
+echo -e "\033[1;33mDesculpe, \033[1;33mvocê precisa executar como root\033[0m"
+rm -rf $HOME/Plus > /dev/null 2>&1; exit 0
+}
+cd $HOME
+fun_bar () {
+comando[0]="$1"
+comando[1]="$2"
+ (
+[[ -e $HOME/fim ]] && rm $HOME/fim
+${comando[0]} -y > /dev/null 2>&1
+${comando[1]} -y > /dev/null 2>&1
+touch $HOME/fim
+ ) > /dev/null 2>&1 &
+ tput civis
+echo -ne "  \033[1;33mWaiting \033[1;37m- \033[1;33m["
+while true; do
+   for((i=0; i<18; i++)); do
+   echo -ne "\033[1;31m#"
+   sleep 0.1s
+   done
+   [[ -e $HOME/fim ]] && rm $HOME/fim && break
+   echo -e "\033[1;33m]"
+   sleep 1s
+   tput cuu1
+   tput dl1
+   echo -ne "  \033[1;33mWaiting \033[1;37m- \033[1;33m["
+done
+echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
+tput cnorm
+}
+
+echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "WELCOME TO DHOOM MANAGER" ; tput sgr0
+echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
+echo ""
+echo -e "             \033[1;31mATTENTION! \033[1;33mMAR to be written !\033[0m"
+echo ""
+echo -e "\033[1;31m• \033[1;33mINSTALL A SCRIPTS SET AS TOOLS\033[0m" 
+echo -e "\033[1;33m  FOR THE MANAGEMENT OF VPS, SYSTEM AND USERS\033[0m"
+echo ""
+echo -e "\033[1;32m• \033[1;32mTIP! \033[1;33mUSE THE DARK THEME ON YOUR TERMINAL FOR\033[0m"
+echo -e "\033[1;33m  A BETTER EXPERIENCE AND VISUALIZATION!\033[0m"
+echo ""
+echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mBY @mooa322 ☆ @mooa_322\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×\033[0m"
+echo ""
+echo -ne "\033[1;36mWaiting... \033[1;32m OK !\033[1;37m "
+chmod +x list && ./list > /dev/null 2>&1
+echo ""
+IP=$(wget -qO- ipv4.icanhazip.com)
+IP2=$(wget -qO- ipv4.icanhazip.com)
+[[ "$IP" != "$IP2" ]] && ipdovps="$IP2" || ipdovps="$IP"
+[[ -f "$HOME/usuarios.db" ]] && {
+    clear
+    echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
+    echo ""
+	echo -e "                 \033[1;33m• \033[1;31mATTENTION \033[1;33m• \033[0m"
+	echo ""
+    echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mWas" 
+    echo -e "Found! Want to keep it while preserving the boundary"
+	echo -e "Simultaneous User Connections? Or Want"
+    echo -e "create a new database ?\033[0m"
+	echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Current Database\033[0m"
+	echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
+	echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
+    echo ""
+	tput setaf 2 ; tput bold ; read -p "What You Want ?: " -e -i 1 optiondb ; tput sgr0
+} || {
+	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+}
+[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' " WAIT FOR INSTALLATION" ; tput sgr0
+echo ""
+echo ""
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mUPDATE SYSTEM \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+echo ""
+echo -e "    \033[1;33mUPDATES USING TO TAKE A LITTLE!\033[0m"
+echo ""
+fun_attlist () {
+    apt-get update -y
+    apt-get install cowsay -y
+    apt-get install ruby -y
+    apt-get install lolcat -y
+    apt-get install toilet -y
+    apt-get install python -y
+    pip install -r /bin/requirements.txt
+}
+fun_bar 'fun_attlist'
+clear
+echo ""
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALLING PACKAGES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "\033[1;33mSOME PACKAGES ARE EXTREMELY REQUIRED !\033[0m"
+echo ""
+inst_pct () {
+_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
+for _prog in ${_pacotes[@]}; do
+    apt install $_prog -y
+done
+pip install speedtest-cli && pip install -r /bin/requirements.txt
+}
+fun_bar 'inst_pct'
+[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
+clear
+echo ""
+echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINISHING \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "      \033[1;33mCOMPLETING FUNCTIONS AND DEFINITIONS! \033[0m"
+echo ""
+clear
+echo ""
+cd $HOME
+echo -e "        \033[1;33m • \033[1;32mINSTALLATION COMPLETED\033[1;33m • \033[0m"
+echo ""
+echo -e "\033[1;31m \033[1;33mUse The Command : \033[1;32mdhoom\033[0m"
+echo -e "\033[1;33m MORE INFORMATION \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@mooa322 @mooa_322\033[0m"
+echo ""
+toilet -f smmono9 "dhoom" |lolcat
+rm -rf $HOME/Plus && rm -rf $HOME/list && cat /dev/null > ~/.bash_history && history -c
+echo "$ipdovps" >/etc/IP
+
